Game engine renderer
nsu-null/null pull request #10
Opened 2021-11-25 10:12 UTC by p-vasilev

2021-11-25 13:39 UTC, ghB111 requested changes

2021-11-25 13:39 UTC, ghB111 commented on CMakeLists.txt
> +add_executable(NULL_GAME main.cpp include/NullGameEngine/RenderLayer.hpp)
![image](https://user-images.githubusercontent.com/42515597/143450207-6b989cb7-9056-435e-8ddb-5b14797e5ecb.png)

2021-11-25 13:39 UTC, ghB111 commented on src/NullGameEngine/GameObject.cpp
> +        //this->renderLayer = BACKGROUND;
Остался коммент

2021-11-25 13:39 UTC, ghB111 commented on src/NullGameEngine/GameObject.cpp
> +    RenderLayer& GameObject::getRenderLayer() {
Я предлагаю сделать поле публичным, потому что `x->getRenderLayer() = BACKGROUND`  немного плохо читается

2021-11-25 13:39 UTC, ghB111 commented on src/NullGameEngine/Renderer.cpp
> +        typedef struct {
Мы придерживаемся современного с++, поэтому здесь имеет смысл использовать using, как мне кажется

2021-11-25 13:39 UTC, ghB111 commented on src/NullGameEngine/Renderer.cpp
> +                auto spriteRefPair = new SpriteRefPair {go->getRenderLayer(), go->getSprite()};
Здесь как будто бы memory leak

2021-11-25 15:13 UTC, ghB111 commented
Кстати, если мы не делаем сейчас никакого кэша (не переиспользуем эту очередь), то написанный код ведь будет эквивалентен тому, чтобы получить список объектов и просто вызвать на него сортировку?

2021-11-25 15:46 UTC, p-vasilev commented on CMakeLists.txt
> +add_executable(NULL_GAME main.cpp include/NullGameEngine/RenderLayer.hpp)
🤡

2021-11-25 15:46 UTC, p-vasilev commented on src/NullGameEngine/GameObject.cpp
> +        //this->renderLayer = BACKGROUND;
упс, забыл раскомментить (лучше уж явно будет выставлено BACKGROUND)

2021-11-25 15:47 UTC, p-vasilev commented on src/NullGameEngine/GameObject.cpp
> +    RenderLayer& GameObject::getRenderLayer() {
ok

2021-11-30 06:34 UTC, ghB111 approved these changes

2021-11-30 06:50 UTC, merged

2021-11-30 06:51 UTC, ghB111 commented
🥳 🎉