New cmake file
nsu-null/null pull request #3
Opened 2021-10-14 04:39 UTC by ghB111

*Всем привет, коллеги!*
Предлагаю вашему вниманию CMakeLists.txt, который я воровал с интернета в течение примерно суток!
Как попробовать:
Возьмите код по [ссылке](https://riptutorial.com/sfml/example/32657/hello-world-in-a-sfml-window), вставьте его в корневую папку как main.cpp. (но нужно будет скачать любой шрифт из интернета, чтобы использовать его в коде)
```cmd
mkdir build
cd build
# для windows будет такая команда, для Linux скорее всего пойдет генератор по умолчанию, то есть -G не надо указывать
# следует проверить это, конечно
cmake -G"MinGW Makefiles" ..
cmake --build .
```

В реальности этот cmake еще надо доделать будет, скорее всего, чтобы include'ы себя хорошо вели, но это потом

2021-10-14 04:52 UTC, Artemonchik commented
Для работы с данным вариантом мне придется использовать mingw?

2021-10-14 12:40 UTC, p-vasilev requested changes
В инклюде поменяй слэш на прямой а так норм :)

2021-10-14 12:40 UTC, p-vasilev commented on main.cpp
> +#include <SFML\Graphics.hpp>
Поменяй на SFML**/**Graphics.hpp чтобы точно было совместимо с линуксом (на винде тоже должно работать)

2021-10-14 12:40 UTC, p-vasilev commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 11)
У нас точно будет стандарт 11? Нужно это обсудить...

2021-10-14 12:40 UTC, p-vasilev commented on CMakeLists.txt
> +set(BUILD_SHARED_LIBS OFF)
Нужно будет быть поаккуратней с этим флагом, если будет билдить динамические библы (просто на заметку)

2021-10-14 12:54 UTC, ghB111 commented on main.cpp
> +#include <SFML\Graphics.hpp>
Есть 😄

2021-10-14 13:28 UTC, p-vasilev approved these changes
👍

2021-10-16 12:28 UTC, sescer approved these changes

2021-10-24 05:33 UTC, merged