Actual Pull request
nsu-null/null pull request #8
Opened 2021-11-16 19:24 UTC by p-vasilev

Я с пулл реквестом налажал лл
@ghB111  ты посмотри там, скажи как оно

2021-11-17 04:15 UTC, ghB111 requested changes
В общем и целом огонь, гораздо лучше чем было, req changes только чтобы поговорить про пару вопросов, которые я там поднял в комментах

2021-11-17 04:15 UTC, ghB111 commented on src/NullGameEngine/ResourceManager.cpp
> +        auto texture = new sf::Texture();
Тут на данный этап все окей, как я думаю, но потом надо будет что-то придумать, потому что пахнет memory leak. Тут потом то ли отдавать unique_ptr, то ли вообще всегда копировать texture, потому что маловесный объект все равно (но тогда и в gameobject нужно хранить его не указателем, а самой сущностью). Но пока окей 🔥

2021-11-17 04:15 UTC, ghB111 commented on src/NullGameEngine/ResourceManager.cpp
> +        auto texture = new sf::Texture();
Но мб если это потом перейдет под smart pointer'ы, то вопрос уйдет

2021-11-17 04:46 UTC, p-vasilev commented on src/NullGameEngine/MainLoop.cpp
> +                std::this_thread::sleep_for(std::chrono::duration<double, std::milli>(1.0));
std::this_thread вроде как не особо связан с std::thread, посмотри...

2021-11-17 04:51 UTC, p-vasilev commented on src/NullGameEngine/MainLoop.cpp
> +                std::this_thread::sleep_for(std::chrono::duration<double, std::milli>(1.0));
да, и почему у нас не было лимита по фреймрейту до сих пор? х)

2021-11-17 04:51 UTC, ghB111 commented on src/NullGameEngine/MainLoop.cpp
> +                std::this_thread::sleep_for(std::chrono::duration<double, std::milli>(1.0));
К сожалению, именно std::this_thread тоже связан, компиляция не проходит. Там тоже он в mingw по какому-то дефайну скрывается в <thread>, судя по всему
![image](https://user-images.githubusercontent.com/42515597/142136798-4ce5e9ff-ae85-49b4-8026-07c97d2bd8c8.png)

2021-11-17 05:01 UTC, ghB111 commented on src/NullGameEngine/MainLoop.cpp
> +                std::this_thread::sleep_for(std::chrono::duration<double, std::milli>(1.0));
> да, и почему у нас не было лимита по фреймрейту до сих пор? х)

)))00)))00)))000
wstaw pozhalusta

2021-11-18 10:19 UTC, ghB111 approved these changes
Все отлично, спасибо за работу, ожидайте начисление скрам-кредитов!
![image](https://user-images.githubusercontent.com/42515597/142396845-05460523-f230-47dd-bb0d-7ca572995a78.png)

2021-11-18 10:19 UTC, ghB111 commented on src/NullGameEngine/MainLoop.cpp
> +    constexpr unsigned int MAX_FRAMERATE = 60;
Вот тут более c++ way написать так. 
https://docs.microsoft.com/en-us/cpp/cpp/constexpr-cpp?view=msvc-170
По функционалу тот же дефайн в таком употреблении, только тайпчекинг получше идет, вроде как.

2021-11-18 10:20 UTC, merged