Game engine physics
nsu-null/null pull request #9
Opened 2021-11-20 08:38 UTC by ghB111

Добавил box2d. В трелло по [карточке](https://trello.com/c/hnkcmCFT/63-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%84%D0%B8%D0%B7%D0%B8%D0%BA%D1%83-%D0%B2-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA) можно посмотреть мои терзания по поводу дизайна
Если есть какие-то очевидные ошибки или где-то что-то можно улучшить -- буду рад услышать

Сейчас там по координатам логика такая: box2d работает в метры*килограммы*секунды, а рисовка в пикселах. Я взял пока что 100 пикселов как 1 м. При этом по box2d координатам выставляются графические. *Таким образом встает вопрос о том, чтобы в будущем ~~(рефакторинге)~~ совсем инкапсулировать координаты спрайта и никому их ни на чтение, ни на редактирование не давать*

2021-11-23 05:55 UTC, ghB111 commented
@p-vasilev забыл реквестнуть ревью. это не срочно, просто хочу, чтобы кто-то на раз хотя бы проверил, нет ли серьезных ошибок

2021-11-23 07:15 UTC, p-vasilev requested changes
Пофикси :)

2021-11-23 07:15 UTC, p-vasilev commented on src/NullGameEngine/GameObject.cpp
> +                sprite.getTexture()->getSize().y * sprite.getScale().y);
Тут 100% нужно использовать `sf::Sprite::getTextureRect` а не `sf::Texture::getSize`, т.к. с анимациями в одной текстуре это *очень* плохо будет работать

2021-11-23 07:15 UTC, p-vasilev commented on src/NullGameEngine/GameObject.cpp
> +            throw std::invalid_argument("No sprite attached, can't guess rigidbody size");
Теоретически у спрайта может не быть текстуры но быть размер и тело (например триггер у которого есть тело-сенсор должен иметь размеры и тело но не текстуру)

2021-11-23 09:44 UTC, ghB111 commented on src/NullGameEngine/GameObject.cpp
> +                sprite.getTexture()->getSize().y * sprite.getScale().y);
Да, я поправлю

2021-11-23 09:44 UTC, ghB111 commented on src/NullGameEngine/GameObject.cpp
> +            throw std::invalid_argument("No sprite attached, can't guess rigidbody size");
Справедливо. Поправлю

2021-11-25 08:43 UTC, p-vasilev approved these changes

2021-11-25 08:44 UTC, merged